#!/usr/bin/env python
"""Run or plan 2D SLAM from a manual-route ROS2 dataset."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from oracle_explorer.io_utils import ensure_dir, read_json, write_json
from oracle_explorer.ros2.rosbag import read_rosbag_metadata
from oracle_explorer.ros2.topics import detect_ros2_environment


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run 2D SLAM from a manual-route ROS2 replay dataset.")
    parser.add_argument("--dataset", required=True)
    parser.add_argument("--slam-backend", default="slam_toolbox", choices=("slam_toolbox",))
    parser.add_argument("--out", required=True)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def _default_bag_path(dataset: Path) -> Path | None:
    metadata_path = dataset / "metadata.json"
    if metadata_path.exists():
        metadata = read_json(metadata_path)
        bag = metadata.get("rosbag_path")
        if bag:
            return Path(bag)
    bag_root = dataset / "rosbag2"
    if bag_root.exists():
        candidates = sorted(p for p in bag_root.iterdir() if p.is_dir())
        if candidates:
            return candidates[0]
    return None


def _ros_pkg_available(package: str) -> bool:
    ros2 = shutil.which("ros2")
    if not ros2:
        return False
    try:
        result = subprocess.run([ros2, "pkg", "list"], check=False, capture_output=True, text=True, timeout=10)
    except Exception:
        return False
    return result.returncode == 0 and package in set(result.stdout.split())


def build_slam_metadata(args: argparse.Namespace) -> dict[str, Any]:
    dataset = Path(args.dataset)
    out = ensure_dir(args.out)
    env = detect_ros2_environment()
    bag_path = _default_bag_path(dataset)
    topics: list[str] = []
    topic_counts: dict[str, int] = {}
    failure_reason = None
    if bag_path and (bag_path / "metadata.yaml").exists():
        bag_meta = read_rosbag_metadata(bag_path)
        topics = bag_meta["topics"]
        topic_counts = bag_meta["message_counts"]
    elif bag_path:
        failure_reason = f"rosbag metadata.yaml missing: {bag_path / 'metadata.yaml'}"
    else:
        failure_reason = "rosbag_not_found"

    if args.slam_backend == "slam_toolbox" and not _ros_pkg_available("slam_toolbox"):
        failure_reason = "slam_toolbox_not_installed"
    required_topics = ["/scan", "/tf", "/odom"]
    missing_topics = [topic for topic in required_topics if topic not in topics]
    if not failure_reason and missing_topics:
        failure_reason = f"required_topics_missing: {missing_topics}"
    if args.dry_run and not failure_reason:
        failure_reason = "dry_run_only"

    success = False
    metadata = {
        "dry_run": bool(args.dry_run),
        "failure_reason": failure_reason,
        "input_rosbag": bag_path.as_posix() if bag_path else None,
        "map_output": {
            "map_pgm": (out / "map.pgm").as_posix(),
            "map_yaml": (out / "map.yaml").as_posix(),
        },
        "ros_environment": env,
        "slam_backend": args.slam_backend,
        "success": success,
        "topic_message_counts": topic_counts,
        "topics_available": topics,
        "topics_used": required_topics,
    }
    write_json(out / "slam_metadata.json", metadata)
    write_json(out / "slam_topics.json", {"available": topics, "required": required_topics, "message_counts": topic_counts})
    (out / "slam_run.log").write_text(
        "SLAM map was not generated by this MVP run.\n"
        f"failure_reason={failure_reason}\n"
        "Install/source ROS2 slam_toolbox and provide a rosbag with /scan, /tf, and /odom to run mapping.\n",
        encoding="utf-8",
    )
    return metadata


def main() -> None:
    args = parse_args()
    metadata = build_slam_metadata(args)
    print(json.dumps(metadata, indent=2, sort_keys=True))
    raise SystemExit(0)


if __name__ == "__main__":
    main()
